name: NX build docker image & deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, build-test]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.AZURE_LOGIN }}
          password: ${{ secrets.AZURE_PASSWORD }}
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v2
        with:
          resource-group: ${{ secrets.AZURE_RESOURCEGROUP }}
          cluster-name: ${{ secrets.AZURE_CLUSTERNAME }}
      - name: build docker base image
        run: |
          mkdir -p ./repo/docker-cache
          XFILE=./repo/docker-cache/base.tar
          if [ -f "$XFILE" ]; then
              echo "$XFILE exists."
              docker load < ./repo/docker-cache/base.tar
          else
            echo "$XFILE does not exist."
            docker build --tag=builder .
            docker save -o ./repo/docker-cache/base.tar builder
          fi

          chmod +x ./tools/docker/*.sh

          mkdir -p k8s
      - uses: actions/download-artifact@v3
      - name: build & push docker images
        run: |
          npm ci
          npx nx affected --target=docker
          npx nx affected --target=deploy
