name: NX build & test

on:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - uses: nrwl/nx-set-shas@v2
      - run: npm ci
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3 --configuration=production
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
